import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body
        className={`min-h-screen bg-gradient-to-tr from-blue-300 to-blue-800 ${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
